name: Slack notification when Create pull request

on:
  pull_request:
    branches:
      - *

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
